<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtJ0TdD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtJ0TdD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtJ0TdD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtJ0TdD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAtJ0TdD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AtJ0TdD',
    'container.build_id' => '4d82190f',
    'container.build_time' => 1561577645,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtJ0TdD');
