<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3ehVRuP\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3ehVRuP/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3ehVRuP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3ehVRuP\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3ehVRuP\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3ehVRuP',
    'container.build_id' => '656e2135',
    'container.build_time' => 1561562912,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3ehVRuP');
