<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU5Tkz00\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU5Tkz00/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU5Tkz00.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU5Tkz00\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU5Tkz00\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U5Tkz00',
    'container.build_id' => '32b8af8e',
    'container.build_time' => 1561622847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU5Tkz00');
