<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'article_index' => [[], ['_controller' => 'App\\Controller\\ArticleController::index'], [], [['text', '/article']], [], []],
    'article_new' => [[], ['_controller' => 'App\\Controller\\ArticleController::create'], [], [['text', '/article']], [], []],
    'article_show' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::read'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'article_inc_views' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::incrementViews'], [], [['text', '/increment'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'article_delete' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'article_update' => [['id'], ['_controller' => 'App\\Controller\\ArticleController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/login']], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/register']], [], []],
    'categories_all' => [[], ['_controller' => 'App\\Controller\\CategoryController::readAll'], [], [['text', '/category']], [], []],
    'category_read' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::read'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'category_article_all' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::readNestedArticles'], [], [['text', '/article'], ['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'category_create' => [[], ['_controller' => 'App\\Controller\\CategoryController::create'], [], [['text', '/category']], [], []],
    'category_upd' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'del_category' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::deleteCategory'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/category']], [], []],
    'search' => [[], ['_controller' => 'App\\Controller\\SearchController::Search'], [], [['text', '/search']], [], []],
    'user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/user']], [], []],
    'is_admin' => [['token'], ['_controller' => 'App\\Controller\\UserController::is_admin'], [], [['text', '/check'], ['variable', '/', '[^/]++', 'token', true], ['text', '/user']], [], []],
];
