<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.AmV4iN5' shared service.

return $this->privates['.service_locator.AmV4iN5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.AmV4iN5.App\\Entity\\User', NULL, 'Cannot autowire service "fos_rest.serializer.form_error_handler.inner": it references class "App\\Entity\\User" but no such service exists.'],
    'violations' => ['privates', '.errored..service_locator.AmV4iN5.Symfony\\Component\\Validator\\ConstraintViolationList', NULL, 'Cannot autowire service "fos_rest.serializer.form_error_handler.inner": it references class "Symfony\\Component\\Validator\\ConstraintViolationList" but no such service exists.'],
], [
    'passwordEncoder' => '?',
    'user' => 'App\\Entity\\User',
    'violations' => 'Symfony\\Component\\Validator\\ConstraintViolationList',
]);
