<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gppUxMa' shared service.

return $this->privates['.service_locator.gppUxMa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'authenticationUtils' => ['services', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
], [
    'authenticationUtils' => '?',
    'passwordEncoder' => '?',
]);
