<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zPdjHdN' shared service.

return $this->privates['.service_locator.zPdjHdN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articles' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'category' => ['privates', '.errored..service_locator.zPdjHdN.App\\Entity\\Category', NULL, 'Cannot autowire service "fos_rest.serializer.form_error_handler.inner": it references class "App\\Entity\\Category" but no such service exists.'],
], [
    'articles' => 'App\\Repository\\ArticleRepository',
    'category' => 'App\\Entity\\Category',
]);
