<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventListener\ArticleUploadListener' shared autowired service.

include_once $this->targetDirs[3].'/src/EventListener/ArticleUploadListener.php';

return $this->privates['App\\EventListener\\ArticleUploadListener'] = new \App\EventListener\ArticleUploadListener(($this->targetDirs[3].'/public/uploads/images'));
