<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.AmV4iN5.Symfony\Component\Validator\ConstraintViolationList' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintViolationListInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintViolationList.php';

return $this->privates['.errored..service_locator.AmV4iN5.Symfony\\Component\\Validator\\ConstraintViolationList'] = new \Symfony\Component\Validator\ConstraintViolationList();
