<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'var_dumper.cloner' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Cloner/ClonerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Cloner/AbstractCloner.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Cloner/VarCloner.php';

$this->services['var_dumper.cloner'] = $instance = new \Symfony\Component\VarDumper\Cloner\VarCloner();

$instance->setMaxItems(2500);
$instance->setMinDepth(1);
$instance->setMaxString(-1);

return $instance;
