<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'var_dumper.command.server_dump' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Command/ServerDumpCommand.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Server/DumpServer.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Command/Descriptor/DumpDescriptorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Command/Descriptor/CliDescriptor.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Command/Descriptor/HtmlDescriptor.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Dumper/DataDumperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Cloner/DumperInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Dumper/AbstractDumper.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Dumper/CliDumper.php';
include_once $this->targetDirs[3].'/vendor/symfony/var-dumper/Dumper/HtmlDumper.php';

$a = new \Symfony\Component\VarDumper\Dumper\HtmlDumper(NULL, 'UTF-8', 0);
$a->setDisplayOptions(['fileLinkFormat' => ($this->privates['debug.file_link_formatter'] ?? ($this->privates['debug.file_link_formatter'] = new \Symfony\Component\HttpKernel\Debug\FileLinkFormatter(NULL)))]);

$this->privates['var_dumper.command.server_dump'] = $instance = new \Symfony\Component\VarDumper\Command\ServerDumpCommand(new \Symfony\Component\VarDumper\Server\DumpServer('tcp://'.$this->getEnv('string:VAR_DUMPER_SERVER'), ($this->privates['logger'] ?? ($this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()))), ['cli' => new \Symfony\Component\VarDumper\Command\Descriptor\CliDescriptor(($this->privates['var_dumper.cli_dumper'] ?? $this->load('getVarDumper_CliDumperService.php'))), 'html' => new \Symfony\Component\VarDumper\Command\Descriptor\HtmlDescriptor($a)]);

$instance->setName('server:dump');

return $instance;
